# Generated by Django 4.0.4 on 2022-05-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up_data', '0002_alter_mydata_id_alter_mydata_myid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='myid',
            field=models.CharField(max_length=1000),
        ),
    ]
